from __future__ import annotations
from typing import Protocol

class CommerceProvider(Protocol):
    def get_order(self, order_id: str) -> dict: ...
    def search_products(self, query: str) -> list[dict]: ...
    def create_draft_order(self, customer_id: str, lines: list[dict]) -> dict: ...

class TicketProvider(Protocol):
    def create_ticket(self, subject: str, summary: str, customer_ref: str | None = None) -> dict: ...
