from .models import Opportunity

SEEDS = [
Opportunity("Practice Statement Normalizer","document_normalizer","UK accountants/bookkeepers",
"Recurring statements require manual cleanup before accounting import","labor_saved",9,8,9,8,8,9,9,9,8,9,2,3,3,
"Start with 3 statement types and one Xero/QuickBooks target."),
Opportunity("Trade Supplier Invoice Normalizer","document_normalizer","UK trades + bookkeepers",
"Supplier invoices need line-item/job coding before job-cost/accounting import","labor_saved",9,8,9,7,8,8,8,9,8,9,2,4,3,
"Wedge is supplier-specific layout + job reference handling."),
Opportunity("Xero Practice Ops Adapter","workflow_adapter","UK accountancy practices",
"Staff repeatedly compile client queries, exceptions and evidence around Xero workflows","labor_saved",10,9,9,6,9,8,8,9,7,10,2,5,5,
"Draft/suggest first; approval before consequential financial changes."),
Opportunity("Field Service Ops Adapter","workflow_adapter","3-30 person trade/service firms",
"Lead->quote->job->follow-up data moves manually across inbox and field system","revenue_and_labor",10,9,10,6,8,8,9,9,7,10,3,5,4,
"Pick one incumbent + trade + country first."),
Opportunity("Public Tender Change Radar","event_monitor","specialist contractors/consultancies",
"Firms miss tenders/amendments across public procurement feeds","revenue_won",9,9,8,8,9,8,9,9,8,9,1,3,2,
"Use official public feeds/APIs; qualify to should-we-bid alert."),
Opportunity("Planning Permit Opportunity Radar","event_monitor","architects/surveyors/installers",
"Local professionals find project opportunities too late","revenue_won",8,9,8,7,8,8,10,9,8,9,2,4,3,
"Geo + classification + entity resolution is the moat."),
Opportunity("Vertical Form Backend","vertical_form_backend","web agencies serving one trade",
"Generic form submissions require manual qualification and CRM entry","labor_and_revenue",10,7,10,9,9,8,8,10,6,8,1,2,2,
"Return a structured job/lead object and webhook, not merely email."),
Opportunity("Legacy Portal Browser Assistant","browser_extension","one profession / one authorized portal",
"Users retype/copy the same structured fields in a legacy portal","labor_saved",8,8,9,8,7,9,10,10,8,9,4,3,4,
"No access-control bypasses; operate inside authorized user session."),
Opportunity("UK Business Identity Validation API","api_aggregator","UK B2B onboarding",
"Apps combine multiple validations and normalize inconsistent identifiers","risk_and_labor",10,8,10,7,8,7,10,9,7,9,2,4,5,
"Bundle lawful data sources; UK-native schema is the wedge."),
Opportunity("Supplier Price List Normalizer","document_normalizer","distributors/installers",
"Weekly supplier files use different SKUs/layouts and require manual merge","labor_and_margin",9,8,10,7,8,7,9,9,8,9,2,4,2,
"Canonical SKU mapping + price-change alerts."),
Opportunity("Certification Renewal Radar","event_monitor","SMBs with staff/equipment certifications",
"Renewal dates are scattered and missed","loss_prevented",8,8,8,9,9,7,9,10,6,9,1,2,3,
"Start CSV/manual evidence; integrate sources later."),
Opportunity("Niche Verified Vendor Directory","directory_data_asset","high-value specialist procurement",
"Buyers cannot filter suppliers by hard operational requirements","revenue_won",8,8,7,7,7,7,10,9,8,8,1,4,3,
"Monetize verification, leads and featured category only after buyer traffic."),
Opportunity("Specialist Job Board Meta Directory","directory_data_asset","fragmented profession",
"Candidates/recruiters search many association/company boards","revenue_won",8,7,8,8,7,8,10,9,7,7,1,3,2,
"Recruiters/boards fund distribution; candidate side free."),
Opportunity("Agency Client Portal Thin Layer","workflow_adapter","small agencies/consultancies",
"Client requests/approvals/files are fragmented across email","labor_saved",7,7,9,8,9,6,8,9,5,8,1,5,2,
"Integrate existing storage/PM tools; don't become a full PSA."),
Opportunity("Data Export Backup for One SaaS","hosted_utility","SMBs using one sticky SaaS",
"Businesses want scheduled readable backups but exports are manual","risk_prevented",8,7,10,7,9,7,9,9,7,8,2,3,3,
"Official API + customer-owned storage + restore path."),
Opportunity("Hosted Open Source Vertical Primitive","hosted_infra","one professional niche",
"Teams want open-source capability without operating it","ops_saved",10,8,10,6,8,6,9,8,6,8,2,5,3,
"Sell SLA/upgrades/backups/policy/templates rather than generic hosting."),
Opportunity("Generic Uptime Monitor","generic_monitor","developers",
"Monitor website uptime","risk_prevented",4,4,10,9,10,3,3,9,1,6,1,3,1,
"Included deliberately as a lower-scoring commoditized baseline."),
Opportunity("Generic PDF Parser","generic_parser","everyone",
"Extract fields from arbitrary PDFs","labor_saved",4,4,6,7,9,3,3,8,2,5,1,5,3,
"Included as a warning: broad AI parsing without workflow ownership is weak."),
Opportunity("Generic Agent Hosting","generic_hosting","AI enthusiasts",
"Deploy an agent without setup","ops_saved",5,5,8,7,8,4,5,7,2,5,3,6,2,
"Evidence suggests workflow-specific adapters outperform generic hosting."),
]
